#MAIN_MODEL: "gpt-3.5-turbo-0125"
#MAIN_MODEL: "gpt-4-1106-preview"
MAIN_MODEL: "gpt-4-0125-preview"
ART_MODEL: "dall-e-3"
PIC_SIZE: "1024x1024"
LOG_LEVEL: "INFO"
PIC_QUALITY: "Standard"
#PIC_QUALITY: "hd"
