MAIN_MODEL: "gpt-4.1-nano-2025-04-14"
#MAIN_MODEL: "gpt-4-1106-preview"
#MAIN_MODEL: "gpt-4-0125-preview"
ART_MODEL: "gpt-image-1"
PIC_SIZE: "1024x1024"
LOG_LEVEL: "INFO"
PIC_QUALITY: "standard"
#PIC_QUALITY: "hd"
